name: build-test-examples
on: [push, workflow_dispatch]

jobs:
  job:
    name: ${{matrix.os}}-${{github.workflow}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - uses: ilammy/msvc-dev-cmd@v1
      - name: "Generate"
        run: |
          cmake --preset=ci
      - name: "Build"
        run: |
          cmake --build --preset=ci
      - name: "Test"
        run: |
          ctest --preset=ci