name: create-release
on:
  push:
    tags:
      - 'v*'

jobs:
  job:
    name: ${{matrix.os}}-${{github.workflow}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - uses: ilammy/msvc-dev-cmd@v1
      - name: "Generate"
        run: |
          cmake --preset=${{matrix.os}}
      - name: "Build"
        run: |
          cmake --build --preset=release-${{matrix.os}}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "out/build/**/AddLib*.zip,out/build/**/AddLib*.tar.gz,out/build/**/AddLib*.deb"
          allowUpdates: true
          token: ${{secrets.GITHUB_TOKEN}}

